language: node_js
node_js:
- "10.16.0"
branches:
  only:
  - develop
notifications:
  slack: binary-academy-2019:zu0JzpVwZUPF9GSv8vPwHcI1
env:
  - SKIP_PREFLIGHT_CHECK=true
  - REACT_APP_SERVER_URL=/
install:
  - . scripts/install.sh
script:
  - . scripts/script.sh
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: BinaryStudioAcademy/bsa-2019-depot
    branch: develop
  bucket: depotbucket
  region: eu-central-1
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: depotbucket
  key: latest.zip
  bundle_type: zip
  application: depot-deploy-app
  deployment_group: depot-deploy-app-group
  region: eu-central-1
  on: *2