language: node_js
node_js:
- "10.16.2"
branches:
  only:
  - master
notifications:
  slack: binary-academy-2019:zu0JzpVwZUPF9GSv8vPwHcI1
install:
  - . scripts/install.sh
script:
  - . scripts/script.sh
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: BinaryStudioAcademy/bsa-2019-depot
    branch: master
  bucket: depotbucket
  region: eu-central-1
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: depotbucket
  key: prod.zip
  bundle_type: zip
  application: depot-prod-app
  deployment_group: depot-prod-app-group
  region: eu-central-1
  on: *2