version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/bsa-2019-depot
hooks:
  AfterInstall:
    - location: scripts/after-install.sh
      runas: ubuntu
  ApplicationStart:
    - location: scripts/app-start.sh
      runas: ubuntu