version: 0.0
os: linux
files:
  - source: /
    destination: /home/git/bsa-2019-depot
permissions:
  - object: /
    pattern: "**"
    owner: git
    group: git
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
  ApplicationStart:
    - location: scripts/app-start.sh
      runas: git
