version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/bsa-2019-depot
# hooks:
#   AfterInstall:
#     - location: /home/ubuntu/bsa-2019-depot/scripts/after-install.sh
#       runas: ubuntu
#   ApplicationStart:
#     - location: /home/ubuntu/bsa-2019-depot/scripts/app-start.sh
#       runas: ubuntu