export const types = {
    //Sync
    AUTHORIZE: 'AUTHORIZE',
    //Async
    LOGIN_ASYNC: 'LOGIN_ASYNC',
    UNAUTHORIZE: 'UNAUTHORIZE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE'
};
