export const types = {
  // Async
  FETCH_REPOSITORIES: 'FETCH_REPOSITORIES',
  FETCH_ACTIVITY: 'FETCH_ACTIVITY',
  // Sync
  FILL_REPOSITORIES: 'FILL_REPOSITORIES',
  FILL_MONTH_COMMITS_ACTIVITY: 'FILL_MONTH_COMMITS_ACTIVITY',
  FILL_ACTIVITY_BY_DATE: 'FILL_ACTIVITY_BY_DATE'
};
